### ISSUE TITLE
GitRepository and Kustomization are not installed when we do helm release or kubectl apply the first time.

### ISSUE THREAD

**Issue by suryapandian** [fluxcd-community/helm-charts#104]
### Describe the bug a clear and concise description of what the bug is.

While using `flux-sync` helm chart, to deploy the flux changes.
I either use `helm template` to get the k8s manifests and do `k apply -Rf folder-name-of-generated-manifests` or do a helm release. In both the cases, I get the error:

```
esource mapping not found for name: "flux-capacitor" namespace: "flux2" from "STDIN": no matches for kind "GitRepository" in version "source.toolkit.fluxcd.io/v1beta2"
ensure CRDs are installed first
resource mapping not found for name: "flux-capacitor" namespace: "flux2" from "STDIN": no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1beta2"
ensure CRDs are installed first
```

However, when I re-run `kubectl apply` it works. So, I suspect that the order in which the crds and crd instances are tried to create or incorrect.

To fix this, we could have a helm hook that ensures that the crds are installed first before the crd instances are created.

Note: I would have raised a fix for this myself but I couldn't find any `.crds.yaml` file for kustomization or gitrepository crds.

### What's your helm version?

3.8.2

### What's your kubectl version?

1.24.1

### What's the chart version?

0.4.0

### What happened?

1. Use flux2-sync
2. Use helm template to create k8s manifests yaml
3. Use kubectl apply to create the resources

Getting the error:
```
resource mapping not found for name: "flux-capacitor" namespace: "flux2" from "STDIN": no matches for kind "GitRepository" in version "source.toolkit.fluxcd.io/v1beta2"
ensure CRDs are installed first
resource mapping not found for name: "flux-capacitor" namespace: "flux2" from "STDIN": no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1beta2"
ensure CRDs are installed first
```

### What you expected to happen?

The CRDs should be installed before the crd instance are tried to be created.

### How to reproduce it?

See the section "what happened?" it has steps to reproduce.

### Enter the changed values of values.yaml?

---
flux2:
  enabled: false
flux2-sync:
  gitRepository:
    spec:
      url: "https://github.com/suryapandian/podinfo"
    spec:
      targetNamespace: sample

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install flux2 ./charts/flux2

or 
```
 helm template flux-templates ./charts/flux2  \
      --namespace sample \
      --values tests/flux2/values.yaml \
      | kubectl apply -f -
 ```

**Comment by stefanprodan** [comment]
This is the expected behavior, you need to use the flux2-sync chart to create GitRepostories and Kustomization after you’ve installed flux2.

**Comment by suryapandian** [comment]
I am having both `flux2` and `flux2-sync` as dependencies in the chart. If `flux2-sync` had a helm hook that waited until the CRD was installed, I will be able to do 
```
helm upgrade --install flux2 ./charts/flux2
```

instead of doing the multipline commands
```
kubectl apply -Rf ./tests/artifacts/flux2/charts/flux2
kubectl apply -Rf ./tests/artifacts/flux2/charts/flux2-sync
```

I am not able to do `helm upgrade --install flux2 ./charts/flux2` because gitrepositories and kustomizations is tried to get applied before the CRDs are installed.

**Comment by stefanprodan** [comment]
> I am having both flux2 and flux2-sync as dependencies in the chart. 

You can't do that, you need to run them one after the other.

**Comment by stefanprodan** [comment]
Also what's the point of using Helm with kubectl? Please see `flux bootstrap` that does all things for you.

**Comment by suryapandian** [comment]
> > I am having both flux2 and flux2-sync as dependencies in the chart.
> 
> You can't do that, you need to run them one after the other.

Okay, will do it one after another. 
Could you please point me to a doc that would help me understand why I cannot do that?

**Comment by stefanprodan** [comment]
@suryapandian Helm can't upgrade CRDs if they are placed in the `/crds` dir, We release CRD updates with every Flux release, so to overcome this Helm limitation we had to place the CRDs in `/templates`.

**Comment by suryapandian** [comment]
hmm thanks Stefan, will read along these.
