### ISSUE TITLE
Rename kustomization.yaml generated by flux2-sync

### ISSUE THREAD

**Issue by suryapandian** [fluxcd-community/helm-charts#105]
### Is your feature request related to a problem ?

While using `flux2-sync` chart the naming of the file `kustomization.yaml` is causing problems during automations where by convention it is considered to be kustomization file of `apiVersion: kustomize.config.k8s.io/v1beta1`.
So, we get the error: `json: unknown field \"spec\"`

### Describe the solution you'd like.

We could rename the file `kustomization.yaml` to `sync-kustomization.yaml` or something else.

### Describe alternatives you've considered.

After the manifests are generated using `helm template`, manually renaming the file `kustomization.yaml` fixes the problem.

### Additional context.

One example would be,

we could give the path of `flux2-sync-templates` as the kustomization path for a flux deployment, in such cases `kustomization.yaml` generated by flux2-sync helm chart.
In such cases, we get the error

```
couldn't make target for path '/tmp/kustomization-3076028919/development/application/flux2/charts/flux2-sync/templates': json: unknown field \"spec\"
```

**Comment by suryapandian** [comment]
If this seems valid, I could raise a PR renaming the file. 
If this doesn't seem valid, please tell me why.

Thanks

**Comment by stefanprodan** [comment]
Only Kustomize config files should be named like that. @suryapandian please change the chart and add `flux-` as a prefix to both gitrepo and kustomization.
