### ISSUE TITLE
[FR] Check if the chart comply to all best practices

### ISSUE THREAD

**Issue by pierluigilenoci** [fluxcd-community/helm-charts#12]
Check if the chart comply to all best practices:
https://helm.sh/docs/chart_best_practices/conventions/

**Comment by dwerder** [comment]
Do you have a tool in mind to check that?

**Comment by pierluigilenoci** [comment]
As far as I know, the only tools available are time and patience because it must be done by hand.

**Comment by dwerder** [comment]
In this case, thats not a real FR or do you plan to open that issue after each merge or for for each PR? ;)

We can mention to stick to https://helm.sh/docs/chart_best_practices/ , but I see nothing more to fix this issue.

**Comment by pierluigilenoci** [comment]
This FR is more of a reminder (for me) to do a one-time check and make sure we're starting from a good foundation.
Then of course it is up to each subsequent PR to verify that no non-compliance are created. 
But there is obviously no way to guarantee it.
At least, we can write in the documentation to stick to the best practices by adding a link to the aforementioned page. 
What do you think about it?

**Comment by dwerder** [comment]
I added a note in the PR template.

**Comment by dwerder** [comment]
I think this one can be closed. Otherwise it will stale forever as just a reminder ticket.
