### ISSUE TITLE
Add ingress objects for notification controller

### ISSUE THREAD

**Issue by roobre** [fluxcd-community/helm-charts#128]
### Is your feature request related to a problem ?

Notification controller [receivers](https://fluxcd.io/flux/components/notification/receiver/) allow forges like github or gitlab to send events when the repository state changes, allowing to reduce latency without unreasonable polling frequencies.

For the notification controller to be reachable, most clusters will require an ingress object in addition to the service (especially since it is hardcoded to `ClusterIP`).

### Describe the solution you'd like.

I believe it will be great if the flux2 helm chart allowed to configure an ingress object from `values.yaml`. This object would be disabled by default to prevent accidental exposure of the notification controller.

### Describe alternatives you've considered.

Adding the ingress object separately from the helm chart is something possible, but causes friction as in order to locate the service from the ingress object, you need to know labels and release names that are defined inside the chart. Having to duplicate these to a separate point makes easy to accidentally misconfigure the ingress object.

### Additional context.

If this is a feature you want to add, please LMK. I have some experience working with charts and I'm open to implement it here.

**Comment by stefanprodan** [comment]
I'm in favour of adding an opt-in ingress v1 definition to the chart.

**Comment by roobre** [comment]
Great, I'll try to find some time to get a PR up soon!
