### ISSUE TITLE
Add annotation support to Pre-Install Job 

### ISSUE THREAD

**Issue by twallac10** [fluxcd-community/helm-charts#145]
### Is your feature request related to a problem ?

When installing the chart on an AKS cluster with an Azure Firewall as egress, the Helm install fails with the following log in the flux-check job:

```
Kubernetes API call failed: Get "https://10.0.0.1:443/version": EOF
```

The IP address 10.0.0.1 is being pulled from the KUBERNETES_SERVICE_HOST env variable that is set.

To set the env variables to use the FQDN instead of IP addresses, Microsoft has released an [annotation](https://github.com/Azure/AKS/releases/tag/2022-07-17):

```
 kubernetes.azure.com/set-kube-service-host-fqdn: "true"

```

### Describe the solution you'd like.

The ability to add annotations in the Flux2 Chart pre-install-job.yaml file under spec.template.metadata.

### Describe alternatives you've considered.

Setting environment variables directly which also isn't supported and a bit more challenging as that would require the API address to be passed in.

**Comment by tjgitdh** [comment]
We are also facing the same issue on the Cluster with Azure firewall.

**Comment by automagicallyio** [comment]
+1
