### ISSUE TITLE
Support passing in extraEnv variables to helmController, notificationController, kustomizationController, sourceController

### ISSUE THREAD

**Issue by bpinske** [fluxcd-community/helm-charts#146]
### Is your feature request related to a problem ?

Support passing in extraEnv variables to helmController, notificationController, kustomizationController, sourceController

### Describe the solution you'd like.

Support passing in extraEnv variables to helmController, notificationController, kustomizationController, sourceController

### Describe alternatives you've considered.

.

**Comment by ravilr** [comment]
this has been addressed in https://github.com/fluxcd-community/helm-charts/pull/179

/close
