### ISSUE TITLE
Upgrade to Flux 0.23.0

### ISSUE THREAD

**Issue by pierluigilenoci** [fluxcd-community/helm-charts#16]
### Is your feature request related to a problem ?

No problem, just keep up with the latest version released. 

### Describe the solution you'd like.

Update the chart to use the new version 

### Describe alternatives you've considered.

None

### Additional context.

Ref: https://github.com/fluxcd/flux2/releases/tag/v0.23.0

**Comment by haarchri** [comment]
my understanding is that we updated it 
https://github.com/fluxcd-community/helm-charts/blob/main/charts/flux2/Chart.yaml#L6

@dwerder  what is your oppinion ?

**Comment by pierluigilenoci** [comment]
@haarchri when I opened the issue I got confused and wrote the version number of the chart and not the software version.

This needs to be updated: https://github.com/fluxcd-community/helm-charts/blob/main/charts/flux2/Chart.yaml#L8

**Comment by pierluigilenoci** [comment]
@dwerder thank you a lot!
