### ISSUE TITLE
Update flux2-notification to `notification.toolkit.fluxcd.io/v1beta2`

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd-community/helm-charts#165]
The manifests in the flux2-notification chart are using `notification.toolkit.fluxcd.io/v1beta1` which has been deprecated upstream. Please update the manifests to v1beta2.

**Comment by sebastiangaiser** [comment]
This is already done: https://github.com/fluxcd-community/helm-charts/blob/main/charts/flux2-notification/templates/alert.yaml and https://github.com/fluxcd-community/helm-charts/blob/main/charts/flux2-notification/templates/provider.yaml
