### ISSUE TITLE
fluxv2-notification schema issue

### ISSUE THREAD

**Issue by VinodReddyE** [fluxcd-community/helm-charts#178]
### Describe the bug a clear and concise description of what the bug is.

We are using fluxv2-notification chart version 1.10.0 and creating secret and provider and alert configurations through terraform.
we are sending below values.yaml to the chart.

chart input:
secretlist:
  - name: slack-token
    value:
      data:
        address: "${slack-url}"
providerlist:
  - name: slack
    spec:
      type: slack
      channel: general
      secretRef:
        name: slack-token
alertlist:
  - name: webapp
    spec:
      providerRef:
        name: slack
      eventSeverity: info
      eventSources:
        - kind: GitRepository
          name: flux-system
        - kind: Kustomization
          name: '*'
          
          
  error description:
           template: flux2-notification/templates/provider.yaml:33:18: executing "flux2-notification/templates/provider.yaml" at <$provider.spec.certSecretRef.name>: nil pointer evaluating interface {}.name
           
  as per the schema   "certSecretRef"  is optional.      

### What's your helm version?

v3.4.1

### What's your kubectl version?

v1.24.0

### What's the chart version?

1.10.0

### What you expected to happen?

secretlist:
  - name: slack-token
    value:
      data:
        address: "${slack-url}"
providerlist:
  - name: slack
    spec:
      type: slack
      channel: general
      secretRef:
        name: slack-token
alertlist:
  - name: webapp
    spec:
      providerRef:
        name: slack
      eventSeverity: info
      eventSources:
        - kind: GitRepository
          name: flux-system
        - kind: Kustomization
          name: '*'

error:  template: flux2-notification/templates/provider.yaml:33:18: executing "flux2-notification/templates/provider.yaml" at <$provider.spec.certSecretRef.name>: nil pointer evaluating interface {}.name

### How to reproduce it?

run fluxv2- notification chart using below values.yaml input

### Enter the changed values of values.yaml?

secretlist:
  - name: slack-token
    value:
      data:
        address: "${slack-url}"
providerlist:
  - name: slack
    spec:
      type: slack
      channel: general
      secretRef:
        name: slack-token
alertlist:
  - name: webapp
    spec:
      providerRef:
        name: slack
      eventSeverity: info
      eventSources:
        - kind: GitRepository
          name: flux-system
        - kind: Kustomization
          name: '*'

### Enter the command that you execute and failing/misfunctioning.

terraform apply with fluxv2-notification chart version 1.10.0

**Comment by yurymuski** [comment]
faced the same issue, chart version 1.11

workaround:
```
          certSecretRef:
            name: false
```
