### ISSUE TITLE
Allow customization of ServiceAccount names

### ISSUE THREAD

**Issue by joaocc** [fluxcd-community/helm-charts#191]
### Is your feature request related to a problem ?

Tyring to integrate flux2 on aws eks addons (https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/26), we need to use the service names for IRSA. 
Other helm charts installed as addons allow this name to be defined externally, thus making it easier to be certain of which name to write in automatically generated AWS IAM policies.

### Describe the solution you'd like.

in the following blocks, recognize an extra field `name` or `accountName`.
```
serviceAccount:
  create: true
  ...
```
If not set (or set to `null`) it would use the default (current name), thus maintaining backward compat.

### Describe alternatives you've considered.

hardwiring the names after looking at chart source

**Comment by stefanprodan** [comment]
Changing the SA names is not allowed in this chart, the chart must match what `flux install` does, the SA name of each controller matches the deployment name which matches the Git repository name. You can safely assume these names will never change in Flux, no matter how is deployed, via Flux CLI, via Flux TF Provider or this chart.

**Comment by joaocc** [comment]
Understood. Thanks for the prompt response.
