### ISSUE TITLE
flux-sync - ref: got "string", expected "map"

### ISSUE THREAD

**Issue by clausa20** [fluxcd-community/helm-charts#22]
### Describe the bug a clear and concise description of what the bug is.

In flux-sync in values.yaml in gitRepository, the ref field expects a string value,
but in gitRepository templates it expects a map value.
`ref: mybranch`
Also I tried to put a map in values.yaml, for example:
```
ref:
  branch: mybranch
```
but I got the same error as specifying just an string.

_Error: Failed to render chart: exit status 1: coalesce.go:202: warning: destination for ref is a table. Ignoring non-table value 
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(GitRepository.spec.ref): invalid type for io.fluxcd.toolkit.source.v1beta1.GitRepository.spec.ref: got "string", expected "map"_

### What's your helm version?

version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"darwin/amd64"}

### What's the chart version?

flux2-sync-0.1.1

### What happened?

In flux-sync in values.yaml in gitRepository, the ref field expects a string value,
but in gitRepository templates it expects a map value.
`ref: mybranch`
Also I tried to put a map in values.yaml, for example:
```
ref:
  branch: mybranch
```
but I got the same error as specifying just an string.

_Error: Failed to render chart: exit status 1: coalesce.go:202: warning: destination for ref is a table. Ignoring non-table value 
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(GitRepository.spec.ref): invalid type for io.fluxcd.toolkit.source.v1beta1.GitRepository.spec.ref: got "string", expected "map"_

### What you expected to happen?

I expect following command is success:
helm diff upgrade  -n flux2 -f flux2-sync-values.yaml flux2-sync fluxcd-community/flux2-sync

### How to reproduce it?

Specify a string value for ref field.

### Enter the changed values of values.yaml?

ref: mybranch

or

ref: 
      branch: mybranch

### Enter the command that you execute and failing/misfunctioning.

helm diff upgrade  -n flux2 -f flux2-sync-values.yaml flux2-sync fluxcd-community/flux2-sync

**Comment by stefanprodan** [comment]
I'm working on a fix, many other things are broken in that chart.
