### ISSUE TITLE
Does it support kubernetes 1.18?

### ISSUE THREAD

**Issue by clausa20** [fluxcd-community/helm-charts#28]
### Is your feature request related to a problem ?

With latest release I get an error in pre-hook that only 1.19 is supported.
Can you support 1.18?
is there some feature that is not supported in 1.18? if yes, could you do some if logic to support both?

Also, please add this kind of information in the main readme.

Thanks.

### Describe the solution you'd like.

Support 1.18 release as well.

### Describe alternatives you've considered.

We think to migrate newer version, but until that, we would be blocked to use this chart until that if you cannot support 1.18.

**Comment by dwerder** [comment]
This check just implements a check which come from flux2 upstream. So you have to raise an issue there if you want support for older k8s versions.

**Comment by dwerder** [comment]
You can also use specific values for the helm install to use older flux images, which maybe support older k8s version.
Any other thought regarding that @stefanprodan ?

**Comment by stefanprodan** [comment]
See here the supported versions https://fluxcd.io/docs/installation/#prerequisites

We have no plans on supporting Kubernetes versions that are EOL.
