### ISSUE TITLE
[FR] Add a conditional option for creating CRDs 

### ISSUE THREAD

**Issue by pierluigilenoci** [fluxcd-community/helm-charts#3]
I will like to have an option like this jetstack/cert-manager@master/deploy/charts/cert-manager/values.yaml#L42

https://github.com/fluxcd-community/helm-charts/blob/dbd6c6af9e50da6689f74f44bccd784efc93030c/charts/flux2/templates/crds/crds-helm-controller.yaml#L1

Created this issue to remind me about https://github.com/fluxcd-community/helm-charts/pull/1#discussion_r740857341

**Comment by haarchri** [comment]
is it possible that the controller runs without the crds ?
can you say more for the use-case ?

**Comment by pierluigilenoci** [comment]
Sometimes some users prefer to manually install the CRDs separately instead of having them installed with the chart.
So if you have to remove the chart to reinstall it you don't lose the CRDs objects already in place.

For example, for the Cert-Manager it makes totally sense because if you install the CRDs with the chart and then remove the chart you lose all the Certificate objects.

**Comment by dmccaffery** [comment]
CRDs should probably be a separate chart (so they can be updated) -- using chart/crds does not support upgrade paths.

**Comment by dmccaffery** [comment]
https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts

**Comment by pierluigilenoci** [comment]
> CRDs should probably be a separate chart (so they can be updated) -- using chart/crds does not support upgrade paths.

A separate chart is even too much, I think that a simple manifest should be enough.
