### ISSUE TITLE
Installing custom resources before a helm upgrade

### ISSUE THREAD

**Issue by neillturner** [fluxcd-community/helm-charts#32]
Thanks for these charts. I always found the flux bootstrap a bit of magical complex install process and the terraform flux provider unable to handle upgrades. 

### Is your feature request related to a problem ?

Currently helm3 when doing an upgrade doesn't upgrade custom resources which can lead to deployment failures because custom resources are not upgraded. 

### Describe the solution you'd like.

I suggest creating in the repo a crds directory and a crds_0.24.0.yaml file with the crds definitions for each chart release. 
then it will be possible to just download the file and then do a 
     helm apply -f  crds_0.24.0.yaml 
before doing the helm upgrade 
if you think thats a good idea then i can create a PR. 

### Describe alternatives you've considered.

alternatively you need to download the chart and extract the crds into file(s) and apply them not a big deal i guess but easy to forget. 
We could just add docs in the readme of that process to remind folks instead of providing the crds file/

**Comment by stefanprodan** [comment]
> Currently helm3 when doing an upgrade doesn't upgrade custom resources

Have you verified that this applies to the flux2 chart?

**Comment by dwerder** [comment]
Alternatively you could do the followiing:

`helm3 apply -f https://github.com/fluxcd-community/helm-charts/blob/flux2-0.6.1/charts/flux2/templates/crd-controller-clusterrole.yaml`

flux2-0.6.1 is the tag of the release. So you can download and apply the crds of the corresponding chart release. We could document this process in the readme.

**Comment by stefanprodan** [comment]
@dwerder how would applying some RBAC help with CRDs upgade?

I don't think what's reported here is true. The flux2 chart doesn't uses the `crds` dir, so Helm should upgrade all CRDs since they are in templates.

**Comment by dwerder** [comment]
@stefanprodan it was just an example, that it is already possible to apply specific crds file for each release. I just took the first file named crd as example.

**Comment by neillturner** [comment]
I don't think what's reported here is true. The flux2 chart doesn't uses the crds dir, so Helm should upgrade all CRDs since they are in templates. - thanks for that. there is alot of confusion as to updgading crds in helm3.
