### ISSUE TITLE
Kustomize controller envFrom helm values

### ISSUE THREAD

**Issue by palassis-8451** [fluxcd-community/helm-charts#35]
### Is your feature request related to a problem ?

If needing to use an [Azure service principal to decrypt sops secrets](https://fluxcd.io/docs/guides/mozilla-sops/#azure), there doesn't currently exist an option to configure one via the helm values.

### Describe the solution you'd like.

Following a similar approach used in [the flux v1 helm chart](https://github.com/fluxcd/helm-operator/issues/312#issuecomment-589022229), would like to propose these values exposed and the kustomize controller template updated (see https://github.com/MxNxPx/helm-charts/tree/kustomize-envFrom).

Updated these files:
* https://github.com/MxNxPx/helm-charts/blob/kustomize-envFrom/charts/flux2/README.md
* https://github.com/MxNxPx/helm-charts/blob/kustomize-envFrom/charts/flux2/values.yaml
* https://github.com/MxNxPx/helm-charts/blob/kustomize-envFrom/charts/flux2/Chart.yaml
* https://github.com/MxNxPx/helm-charts/blob/kustomize-envFrom/charts/flux2/templates/kustomize-controller.yaml

### Describe alternatives you've considered.

NONE

### Additional context.

The following branch should be ready for submitting a PR if sign off is given: https://github.com/MxNxPx/helm-charts/tree/kustomize-envFrom

**Comment by dwerder** [comment]
Without digging to deep into that. Just a question.  Does the secret mount does not work her as well?
https://github.com/fluxcd-community/helm-charts/blob/main/charts/flux2/values.yaml#L128
```
kustomizecontroller:
  # Defines additional mounts with secrets. Secrets must be manually created in the namespace.
  extraSecretMounts: []
    # - name: secret-files
    #   mountPath: /etc/secrets
    #   subPath: ""
    #   secretName: secret-files
    #   readOnly: true```

**Comment by MxNxPx** [comment]
My understanding is that would not work because I cannot specify an environment variable within the controller for it to pull from the secret mount.  Also I thought it might be more confusing to go a different route than what the flux documentation specifies.

**Comment by palassis-8451** [comment]
@dwerder - If there are no other questions, I am happy to create a pull request, but I believe I need someone to sign off first.  Is that correct?  Thanks!

**Comment by haarchri** [comment]
please open the PR you need to sign your commit for example `git commit -sm "commit with dco"` thanks

**Comment by palassis-8451** [comment]
> please open the PR you need to sign your commit for example `git commit -sm "commit with dco"` thanks

Thanks @haarchri, pull request is ready: https://github.com/fluxcd-community/helm-charts/pull/36/

**Comment by MxNxPx** [comment]
> > please open the PR you need to sign your commit for example `git commit -sm "commit with dco"` thanks
> 
> Thanks @haarchri, pull request is ready: #36

Closed the pull request per convo with @dwerder and he offered to open a new one.
