### ISSUE TITLE
Add @dwerder as a helm-charts maintainer

### ISSUE THREAD

**Issue by haarchri** [fluxcd-community/helm-charts#37]
@dwerder has been contributing significant features to `helm-charts`  over the [past few weeks](https://github.com/fluxcd-community/helm-charts/commits?author=dwerder) He has also been responsive and reactive to opened issues and fixes.

This issue proposes adding @dwerder as a `helm-charts` maintainer. Existing maintainers should indicate votes in the comments.

/cc @stefanprodan @hiddeco @pierluigilenoci

**Comment by dwerder** [comment]
Got the invite. Thanks.
