### ISSUE TITLE
[FR] Publication on artifacthub.io

### ISSUE THREAD

**Issue by pierluigilenoci** [fluxcd-community/helm-charts#5]
When the chart is sufficiently mature it must be published on artifacthub.io

**Comment by haarchri** [comment]
@pierluigilenoci  we published our helm-charts:
https://artifacthub.io/packages/helm/fluxcd-community/flux2

@dmccaffery  is it possible that we can move the fluxcd-community to a fluxcd org in artifactoryhub ?

**Comment by dmccaffery** [comment]
I don't work for weave, so... no idea :-D

**Comment by hiddeco** [comment]
Can you open an issue / request for this in `fluxcd/community`?

**Comment by haarchri** [comment]
done https://artifacthub.io/packages/helm/fluxcd-community/flux2
