### ISSUE TITLE
Start using semver version 1.x.x for the charts

### ISSUE THREAD

**Issue by dwerder** [fluxcd-community/helm-charts#62]
### Is your feature request related to a problem ?

To reflect breaking changes in a chart you would start to increase the major semver number. So all chart version are a 0.x at the moment thats a problem. PR #61 is a good example.

### Describe the solution you'd like.

I would like to release a version 1.x of each chart. So we can make it obvios, if we release a chart with breaking changes and increase the major numbers.

### Describe alternatives you've considered.

Maybe we collect some features we want to provide in the first 1.x releases. (IMHO we use this charts already, so I would just give it a 1.x)

**Comment by stefanprodan** [comment]
I'm for releasing v1.0.0 for all charts.
