### ISSUE TITLE
flux2-chart: Pre-Install Hook fails when PSPs are in place

### ISSUE THREAD

**Issue by steveizzle** [fluxcd-community/helm-charts#65]
### Describe the bug a clear and concise description of what the bug is.

When you have PSPs or anything equivalent set up in the cluster which denies Pods from running as root, the Installation of the helm chart will fail, because of the failing Pre-install hook (fux-cli seems to be running as root by default). There is currently also no workaround for this (ok, one very dirty of giving the default service account those privileged rights), because postrender scripts are not evaluated for helm hooks because of a bug in helm (https://github.com/helm/helm/issues/7891). 

### What's your helm version?

v3.7.0

### What's your kubectl version?

v1.22.2

### What's the chart version?

flux2-0.8.6

### What happened?

Installation fails

### What you expected to happen?

Installation succeeds 

### How to reproduce it?

1. Setup PSPs wich require runAsNonRoot
2. Install Chart

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

helm install flux2 fluxcd-community/flux2 -n flux-system

### Anything else we need to know?

There should be some easy solutions for this like 
- running pod as non-root (runAsUser: 10000 should be sufficiant because this pod only executes the one command, which is possible with every uid) like so https://github.com/steveizzle/helm-charts-1/commit/7b5c0c3c44d32b4300914701f0721d2f54c54554
- or the possibility of having a dedicated serviceAccount for the job (which then can be bound to a role with a special psp) like so https://github.com/steveizzle/helm-charts-1/commit/be2a34b54fd95a26dd8039abab8f183c11ee88b0

i could also help implementing it

**Comment by pierluigilenoci** [comment]
Thank you @steveizzle, feel free to open a PR.
