### ISSUE TITLE
[FR] Allow the Chart to create extra manifest

### ISSUE THREAD

**Issue by pierluigilenoci** [fluxcd-community/helm-charts#71]
### Is your feature request related to a problem ?

Sometimes, accessory to the installation there may be manifest to be installed (for example a SecretProviderClass).

### Describe the solution you'd like.

It would be nice to be able to do this directly via the Chart using the approach that ArgoCD also uses.

Ref: https://github.com/argoproj/argo-helm/blob/cf57a71a154a1a8a19f5f9d3980d60eb3efd80c8/charts/argo-cd/values.yaml#L62-L87

### Describe alternatives you've considered.

I don't think there are alternatives

**Comment by dwerder** [comment]
Maybe I am a little bit to overcautious, but that basically means that I allow someone to install everything he likes with the chart. From a security perspective I don't like that. I see that this point was not discussed on the other projects like Grafana and ArgoCD.

https://github.com/argoproj/argo-helm/pull/1094
https://github.com/grafana/helm-charts/pull/974

**Comment by pierluigilenoci** [comment]
@dwerder I saw that they have already answered you in the issue of the other projects but I am also writing it here for completeness and for those who, in the future, should read the discussion.

Helm has the right to install only and exclusively what the "RBAC user" has the right to install.
Just as it could with any static manifest.

The security check must be upstream.
Helm is only a tool to create manifests starting from templates with a minimum of logic and apply them to K8s.
It is not a tool for managing access rights to resources.
