### ISSUE TITLE
Can I pre configure a cluster?

### ISSUE THREAD

**Issue by jurgen-weber-deltatre** [fluxcd-community/helm-charts#88]
### Is your feature request related to a problem ?

I am trying to wrap my head around flux and how it works and then once I am there work out what the best installation method is for our situation. Right now this helm chart and the terraform method are both appealing to me because we have an extensive Terraform base.

Most howto's and instructions on how to setup a clusters take you to the CLI, which is something I won't be able to do: example:

https://github.com/fluxcd/flux2-kustomize-helm-example#bootstrap-staging-and-production

```
flux bootstrap github \
    --context=staging \
    --owner=${GITHUB_USER} \
    --repository=${GITHUB_REPO} \
    --branch=main \
    --personal \
    --path=clusters/staging
```

Is there a way in this chart to complete this setup?

### Describe the solution you'd like.

Some sort of secret that one the chart is applied I can create that creates this config or better yet a secret in the chart. 

### Describe alternatives you've considered.

so far apart from the CLI method, I have only found this method in the terraform provider.

https://registry.terraform.io/providers/fluxcd/flux/latest/docs/guides/github

https://registry.terraform.io/providers/fluxcd/flux/latest/docs/data-sources/sync

### Additional context.

Ohhhhhhhhhhhhhhh, it just dawned on me..... Is that what the flux2-sync chart is for in this repo? Please confirm. Maybe some doco and examples should be created in this repo and you can use my feature request here as a corner stone for an example.

**Comment by dwerder** [comment]
Just a week since you asked and maybe you figured it out by yourself, but your last thought seems to be right. To configure gitrepositories your use the flux2-sync chart.

**Comment by jurgen-weber-deltatre** [comment]
maybe someone following this journey and this info will help them. The bit that really tricked me is the resources it makes needs to be named flux-system.

**Comment by glitchcrab** [comment]
Just to follow up on this (I know the issue is closed) - some documentation as what each chart is for would be great. It's really difficult to translate the outcome of the magic of `flux bootstrap` into these charts.
