### ISSUE TITLE
Publish the Helm charts to GHCR

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd-community/helm-charts#91]
With Helm OCI being GA, I think we should also publish the charts to GitHub Container Registry. An example of how to push to GHCR from GH Actions can be found here: https://github.com/stefanprodan/podinfo/blob/master/.github/workflows/release.yml#L71

PS. After we push the charts to GHCR, we need to use the GH UI and make the images public.

**Comment by dmccaffery** [comment]
Would we want to backfill all previous releases as well?

**Comment by stefanprodan** [comment]
@dmccaffery it would be nice to have all versions but I don't think it's a must.

**Comment by dmccaffery** [comment]
Dependencies:

https://github.com/helm/chart-releaser/issues/183
https://github.com/helm/chart-releaser-action/issues/107

I'm going to work my way through these today.
